---
name: Run pre-commit
on:
  push:
    branches:
      - develop
      - main
  pull_request:
jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
        with:
          python-version: '3.9'
      - name: Install poetry
        shell: bash
        run: |
          echo "Python version is $(python -V)"
          pip install --upgrade pip wheel poetry
          poetry install
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
